

export interface Team {
  id: string;
  name: string;
  roomId: string;
  isReady: boolean;
  score: number;
  winnings: number; // Secured chips from wins
  strategy?: RoundStrategy[]; // Array of 10 rounds
  members: string[]; // List of user names joined
}

export interface RoundStrategy {
  round: number;
  card: number; // 0-9
  chips: number; // Chips wagered/allocated
}

export type RoundResult = 'A_WON' | 'B_WON' | 'DRAW' | 'A_FOLDED' | 'B_FOLDED';

export interface Match {
  id: string;
  teamAId: string;
  teamBId: string;
  teamAScore: number; // Rounds won
  teamBScore: number; // Rounds won
  
  // Game State
  currentRound: number;
  roundStatus: 'READY' | 'DECISION' | 'SHOWDOWN' | 'FINISHED'; 
  turnOwner?: string; // Team ID who needs to make a decision (Fold/Call)
  pot: number; // Current chips in the pot for this round
  carryOver: number; // Chips carried over from previous draws
  
  history: RoundHistory[];
  aiHelps: Record<string, number>; // teamId -> count used
  aiAdvice?: Record<string, string>; // teamId -> active advice text (for syncing)
  
  winnerId?: string;
}

export interface RoundHistory {
  round: number;
  teamACard: number;
  teamBCard: number;
  teamAChips: number;
  teamBChips: number;
  result: RoundResult;
  potWon: number;
}

export interface Room {
  id: string;
  name: string;
  totalTeams: number;
  currentRound: number; // Global round indicator if needed
  status: 'WAITING' | 'PREPARING' | 'PLAYING' | 'FINISHED';
  teams: Team[];
  matches: Match[];
  feedback?: string; // Gemini Feedback
  winnerPhotoUrls?: string[]; // Uploaded by Admin (Changed to array)
  winnerPosterUrl?: string; // Generated by Gemini
}

export interface AdminState {
  isAuthenticated: boolean;
}

export const ADMIN_PW = "6749467";
export const TOTAL_ROUNDS = 10;
export const TOTAL_CHIPS = 30;
export const CARDS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

// --- Landing Page Builder Types ---

export interface LandingPageStyle {
  id: string;
  name: string;
  description: string;
  imageUrl: string;
}

export interface UploadedFile {
  name: string;
  mimeType: string;
  data: string; // base64
}

export interface UserRequirements {
  appName: string;
  keyFeatures: string;
  targetUser: string;
  targetDevices: string[];
  autoGenerationOptions: string[];
  headerNavItems: string;
  referenceContent: string;
  otherRequests: string;
  uploadedFiles: UploadedFile[];
  selectedFeatureIds: string[];
}

export interface FeatureItem {
  id: string;
  name: string;
  description: string;
  category: string;
}